DROP TABLE IF EXISTS `emp` CASCADE;
CREATE TABLE `emp` (
	`id` BIGINT PRIMARY KEY AUTO_INCREMENT, 
	`age` INTEGER CHECK (age<=70 AND age>=18), 
	`gender` VARCHAR(255), 
	`address` VARCHAR(255), 
	`name` VARCHAR(255) NOT NULL UNIQUE
);